### ISSUE TITLE
Realease version 2.5

### ISSUE THREAD

**Issue by hoaphumanoid** [hoaphumanoid/sciblog#6]
Version 2.5 of the blog

- [x]  Auto renew of SSL certificate: #4 
- [x]  Reduce padding and margin in about section for mobile
- [x]  Change titles to be to the left instead of justified
- [x]  Fix bullet point in mobile: #7 
- [x]  Add check spelling
- [x]  Fix ckeditor for new browsers:  #5

**Comment by hoaphumanoid** [comment]
Updated to [tag 2.5](https://github.com/hoaphumanoid/sciblog/releases/tag/2.5)
